### ISSUE TITLE
Underline below the "OPEN" in main page gets displaced on refreshing the page

### ISSUE THREAD

**Issue by titan-rocky** [bitspaceorg/bitspace-org-in#27]
## Issue
When i open the site for the first time, it's in the correct position, but after i reload the page, it gets displaced a bit.

### How to Reproduce
* Open the website
* Reload it

#### Before Reloading
![screenshot-20230826-034939Z-all](https://github.com/bitspaceorg/bitspace-org-in/assets/66237117/6e4f0c79-8d3d-4528-9329-65cd00eff59e)
#### After Reloading
![screenshot-20230826-034943Z-all](https://github.com/bitspaceorg/bitspace-org-in/assets/66237117/2c912eee-2761-4302-b911-e5787dc62b07)

**Comment by RahulNavneeth** [comment]
We will have to wait till we hear from others too re the issue - I am certainly not getting the issue myself

**Comment by titan-rocky** [comment]
After the recent commit, there has been no issues now.
