### ISSUE TITLE
Improving the Metadata

### ISSUE THREAD

**Issue by titan-rocky** [bitspaceorg/bitspace-org-in#3]
The description in the metadata is very good, but while sharing the website link, it should have a rich embed such that it will look appealing. I am looking forward to work on it myself if this issue has been assigned to me. Thanks for reading <3

**Comment by RahulNavneeth** [comment]
Sure yeah, we will have to implement dynamic meta data or something like github's meta link - we can pre-render img and pass it to meta data img

**Comment by RahulNavneeth** [comment]
For ref - https://github.com/RahulNavneeth/hereisasummaprojectformetaimage

https://hereisasummaprojectformetaimage.vercel.app/albert
